### ISSUE TITLE
The function ARN must reference a specific function version

### ISSUE THREAD

**Issue by arbaz-sf** [serverless-operations/serverless-lambda-edge-pre-existing-cloudfront#37]
Hi Team,

I am getting below error while deploying my edge lambda

ServerlessError: The function ARN must reference a specific function version. (The ARN must end with the version number.) ARN: arn:aws:lambda:us-east-1:{AccountID}:function:pim-integration-service-dev-orginRequestEdge:$LATEST
at /usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:343:27
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by arbaz-sf** [comment]
I can see there there is no version in the deployed lambda function
